// goal_id: EMBER-02
// workstream_id: EMBER-02A
// next_executed_outcome: EMBER-02 first sufficiently pretrained clean-genesis 3B Ember
// generate-version.ts — writes generated/version.ts from package.json's "version" field, so the
// compiled binary shows the real build version without depending on an env var being set at
// launch time (B7 gate ask, 2026-07-03: a welcome screen permanently reading v0.0.0 via a
// nowhere-set EMBER_VERSION env var is a real-user-visible defect, not a harness quirk).
//
// Run as part of `bun run build` (package.json), before `bun build --compile`, so the generated
// constant is baked into the standalone exe at compile time.
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

export function versionFileContents(pkg: { version: string }): string {
  return `// AUTO-GENERATED by build-tools/generate-version.ts from package.json's "version" field.
// Do not hand-edit -- re-run the generator (part of \`bun run build\`) to refresh.
export const EMBER_VERSION = ${JSON.stringify(pkg.version)};
`;
}

if (import.meta.main) {
  const here    = dirname(fileURLToPath(import.meta.url));
  const pkgPath = join(here, "..", "package.json");
  const outDir  = join(here, "..", "generated");
  const outPath = join(outDir, "version.ts");

  const pkg = JSON.parse(readFileSync(pkgPath, "utf-8")) as { version: string };
  mkdirSync(outDir, { recursive: true });
  writeFileSync(outPath, versionFileContents(pkg));
  process.stdout.write(`[generate-version] wrote ${outPath} (EMBER_VERSION=${pkg.version})\n`);
}
