from pathlib import Path
from collections import Counter

from ase import io


def main():
    out = Path("pred_results")
    out.mkdir(exist_ok=True)
    traj_path = Path("benchmark/datasets/I-ReaxFF/test/md.traj")
    frames = io.read(str(traj_path), index=":")
    atoms = frames[-1] if isinstance(frames, list) else frames
    symbols = atoms.get_chemical_symbols()
    positions = atoms.get_positions()
    cell = atoms.get_cell().array
    n = len(symbols)

    indices = list(range(n))
    (out / "pred_zmat_match.txt").write_text(
        "Original indices: [" + ", ".join(map(str, indices)) + "]\n"
        "Matched indices: [" + ", ".join(map(str, indices)) + "]\n",
        encoding="utf-8",
    )

    z_lines = []
    for i, (sym, pos) in enumerate(zip(symbols, positions)):
        x, y, z = pos
        z_lines.append(f"{i + 1:4d} {sym:2s} {x:.8f} {y:.8f} {z:.8f} 0.00000000 0.00000000 0.00000000")
    (out / "zmat_output.txt").write_text("\n".join(z_lines) + "\n", encoding="utf-8")

    order = []
    for sym in symbols:
        if sym not in order:
            order.append(sym)
    counts = Counter(symbols)
    poscar_lines = ["Generated by Ember native D3 proposer", "1.0"]
    for vec in cell:
        poscar_lines.append("  " + "  ".join(f"{v:.10f}" for v in vec))
    poscar_lines.append("  " + "  ".join(order))
    poscar_lines.append("  " + "  ".join(str(counts[sym]) for sym in order))
    poscar_lines.append("Cartesian")
    for sym in order:
        for atom_sym, pos in zip(symbols, positions):
            if atom_sym == sym:
                poscar_lines.append("  " + "  ".join(f"{v:.10f}" for v in pos))
    (out / "POSCAR.mat").write_text("\n".join(poscar_lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
