# goal_id: EMBER-02
# workstream_id: EMBER-02A
# next_executed_outcome: EMBER-02 first sufficiently pretrained clean-genesis 3B Ember
from __future__ import annotations

import copy
import unittest

from scripts.github.live_pr_policy import validate_live_pull_request


BASE = "a" * 40
HEAD = "b" * 40


def human_body() -> str:
    sections = {
        "Linked issue or governing contract": "Relates to #1183",
        "Exact base SHA": BASE,
        "Exact reviewed head SHA": HEAD,
        "Intended outcome": "Correct the GitHub work-system enforcement.",
        "Why this is one coherent PR": "One correction and rollback boundary.",
        "Affected areas": "area:ci, area:governance",
        "Affected milestones": "EMBER-02",
        "Implementation summary": "Trusted enforcement and truthful metadata.",
        "Acceptance-clause mapping": "Each clause maps to a named test.",
        "Local reproduction commands": "python -B -m unittest",
        "Automated tests": "Policy unit and integration tests.",
        "Executed evidence": "Exact-head tests and repository guard.",
        "Generated receipts and artifacts": "A content-addressed correction receipt.",
        "Known failures": "None in the bounded scope.",
        "Unverified areas": "Scientific and capability claims.",
        "Claim boundary": "No model, training, or capability claim.",
        "Review provenance": "Independent exact-head review required before merge.",
        "Rollback or revert procedure": "git revert the remediation merge commit.",
        "Follow-up obligations that remain": "Append the correction to PR #1183.",
    }
    body = (
        "<!-- ember-template: pr/governance@v1 -->\n"
        "goal_id: EMBER-02\n"
        "workstream_id: EMBER-02A\n"
        "next_executed_outcome: EMBER-02 first sufficiently pretrained clean-genesis 3B Ember\n"
    )
    return body + "".join(f"\n## {key}\n\n{value}\n" for key, value in sections.items())


def human_pr() -> dict[str, object]:
    return {
        "actor_login": "wordingone",
        "title": "fix(governance): enforce the live GitHub work policy",
        "body": human_body(),
        "base_sha": BASE,
        "head_sha": HEAD,
        "event_base_sha": BASE,
        "event_head_sha": HEAD,
        "draft": False,
        "labels": [
            "kind:governance",
            "area:ci",
            "area:governance",
            "state:ready",
            "priority:p1",
            "review:self-only",
        ],
        "milestone": "EMBER-02",
        "changed_files": [
            ".github/workflows/repo-policy-gate.yml",
            "scripts/github/live_pr_policy.py",
        ],
    }


class LivePullRequestPolicyTests(unittest.TestCase):
    def test_accepts_native_dependabot_title_under_closed_bot_schema(self) -> None:
        snapshot = human_pr()
        snapshot.update(
            {
                "actor_login": "dependabot[bot]",
                "title": "Bump actions/checkout from 4.4.0 to 7.0.1",
                "body": "Generated by Dependabot.",
                "milestone": None,
                "labels": [
                    "kind:maintenance", "area:ci", "state:ready", "priority:p3"
                ],
                "changed_files": [".github/workflows/ci-pr.yml"],
            }
        )
        self.assertEqual([], validate_live_pull_request(snapshot))

    def test_valid_human_pr_passes(self) -> None:
        self.assertEqual([], validate_live_pull_request(human_pr()))

    def test_human_pr_requires_live_metadata_and_semantic_sections(self) -> None:
        for field, replacement, expected in (
            ("title", "Fix policy", "title"),
            ("base_sha", "c" * 40, "event-base"),
            ("head_sha", "c" * 40, "event-head"),
            ("milestone", None, "milestone"),
            ("body", human_body().replace("## Claim boundary", "## Missing"), "Claim boundary"),
        ):
            value = human_pr()
            value[field] = replacement
            with self.subTest(field=field):
                self.assertTrue(
                    any(expected in error for error in validate_live_pull_request(value))
                )

    def test_human_pr_enforces_label_cardinality_and_live_milestone(self) -> None:
        value = human_pr()
        value["labels"] = [*value["labels"], "kind:defect"]
        self.assertIn("labels:kind-cardinality", validate_live_pull_request(value))
        value = human_pr()
        value["milestone"] = "EMBER-03"
        self.assertIn("milestone:body-live-mismatch", validate_live_pull_request(value))

    def test_dependabot_has_closed_narrow_schema(self) -> None:
        value = {
            "actor_login": "dependabot[bot]",
            "title": "build(deps): bump actions/checkout from 5 to 6",
            "body": "Bumps actions/checkout from 5 to 6.",
            "base_sha": BASE,
            "head_sha": HEAD,
            "event_base_sha": BASE,
            "event_head_sha": HEAD,
            "draft": False,
            "labels": [
                "kind:maintenance",
                "area:ci",
                "state:ready",
                "priority:p3",
            ],
            "milestone": None,
            "changed_files": [".github/workflows/ci-pr.yml"],
        }
        self.assertEqual([], validate_live_pull_request(value))
        for mutation, expected in (
            ({"title": "feat(runtime): add a feature"}, "dependabot:title"),
            ({"changed_files": ["scripts/github/policy.py"]}, "dependabot:path"),
            ({"labels": ["kind:feature", "area:ci", "state:ready", "priority:p3"]}, "dependabot:labels"),
        ):
            bad = copy.deepcopy(value)
            bad.update(mutation)
            with self.subTest(mutation=mutation):
                self.assertTrue(
                    any(expected in error for error in validate_live_pull_request(bad))
                )

    def test_unknown_fields_and_non_string_file_paths_fail_closed(self) -> None:
        value = human_pr()
        value["unexpected"] = True
        self.assertIn("snapshot:unknown-fields:unexpected", validate_live_pull_request(value))
        value = human_pr()
        value["changed_files"] = [None]
        self.assertIn("snapshot:changed-files-invalid", validate_live_pull_request(value))


if __name__ == "__main__":
    unittest.main()
