# goal_id: EMBER-02
# workstream_id: EMBER-02A
# next_executed_outcome: EMBER-02 first sufficiently pretrained clean-genesis 3B Ember
from __future__ import annotations

import copy
import os
import pathlib
import shutil
import subprocess
import tempfile
import unittest

import yaml

from scripts.github.live_pr_policy import (
    pinned_head_covers_live_head,
    validate_live_pull_request,
)


BASE = "a" * 40
HEAD = "b" * 40


def human_body() -> str:
    sections = {
        "Linked issue or governing contract": "Relates to #1183",
        "Exact base SHA": BASE,
        "Exact reviewed head SHA": HEAD,
        "Intended outcome": "Correct the GitHub work-system enforcement.",
        "Why this is one coherent PR": "One correction and rollback boundary.",
        "Affected areas": "area:ci, area:governance",
        "Affected milestones": "EMBER-02",
        "Implementation summary": "Trusted enforcement and truthful metadata.",
        "Acceptance-clause mapping": "Each clause maps to a named test.",
        "Local reproduction commands": "python -B -m unittest",
        "Automated tests": "Policy unit and integration tests.",
        "Executed evidence": "Exact-head tests and repository guard.",
        "Generated receipts and artifacts": "A content-addressed correction receipt.",
        "Known failures": "None in the bounded scope.",
        "Unverified areas": "Scientific and capability claims.",
        "Claim boundary": "No model, training, or capability claim.",
        "Review provenance": "Independent exact-head review required before merge.",
        "Rollback or revert procedure": "git revert the remediation merge commit.",
        "Follow-up obligations that remain": "Append the correction to PR #1183.",
    }
    body = (
        "<!-- ember-template: pr/governance@v1 -->\n"
        "goal_id: EMBER-02\n"
        "workstream_id: EMBER-02A\n"
        "next_executed_outcome: EMBER-02 first sufficiently pretrained clean-genesis 3B Ember\n"
    )
    return body + "".join(f"\n## {key}\n\n{value}\n" for key, value in sections.items())


def human_pr() -> dict[str, object]:
    return {
        "actor_login": "wordingone",
        "title": "fix(governance): enforce the live GitHub work policy",
        "body": human_body(),
        "base_sha": BASE,
        "head_sha": HEAD,
        "event_base_sha": BASE,
        "event_head_sha": HEAD,
        "draft": False,
        "labels": [
            "kind:governance",
            "area:ci",
            "area:governance",
            "state:ready",
            "priority:p1",
            "review:self-only",
        ],
        "milestone": "EMBER-02",
        "changed_files": [
            ".github/workflows/repo-policy-gate.yml",
            "scripts/github/live_pr_policy.py",
        ],
    }


class LivePullRequestPolicyTests(unittest.TestCase):
    def test_dependabot_github_actions_prefix_matches_live_policy(self) -> None:
        config_path = pathlib.Path(__file__).parents[2] / ".github" / "dependabot.yml"
        config = yaml.safe_load(config_path.read_text(encoding="utf-8"))
        updates = [
            update
            for update in config["updates"]
            if update.get("package-ecosystem") == "github-actions"
        ]
        self.assertEqual(len(updates), 1)
        self.assertEqual(
            updates[0].get("commit-message", {}).get("prefix"),
            "build(deps)",
        )

    def test_accepts_native_dependabot_title_under_closed_bot_schema(self) -> None:
        snapshot = human_pr()
        snapshot.update(
            {
                "actor_login": "dependabot[bot]",
                "title": "Bump actions/checkout from 4.4.0 to 7.0.1",
                "body": "Generated by Dependabot.",
                "milestone": None,
                "labels": [
                    "kind:maintenance", "area:ci", "state:ready", "priority:p3"
                ],
                "changed_files": [".github/workflows/ci-pr.yml"],
            }
        )
        self.assertEqual([], validate_live_pull_request(snapshot))

    def test_accepts_observed_dependabot_chore_dependency_bump_only(self) -> None:
        snapshot = human_pr()
        snapshot.update(
            {
                "actor_login": "dependabot[bot]",
                "title": (
                    "chore(deps): bump actions/upload-artifact "
                    "from 4.6.2 to 7.0.1"
                ),
                "body": "Generated by Dependabot.",
                "milestone": None,
                "labels": [
                    "kind:maintenance", "area:ci", "state:ready", "priority:p3"
                ],
                "changed_files": [".github/workflows/ci-pr.yml"],
            }
        )
        self.assertEqual([], validate_live_pull_request(snapshot))

        deps_dev = copy.deepcopy(snapshot)
        deps_dev["title"] = "chore(deps-dev): bump actions/checkout from 4 to 5"
        self.assertEqual([], validate_live_pull_request(deps_dev))

        for title in (
            "chore(ci): bump actions/upload-artifact from 4.6.2 to 7.0.1",
            "chore(deps): update actions/upload-artifact from 4.6.2 to 7.0.1",
            "chore(dependencies): bump actions/upload-artifact from 4.6.2 to 7.0.1",
            "chore(deps): bump\nforge a second title line",
        ):
            bad = copy.deepcopy(snapshot)
            bad["title"] = title
            with self.subTest(title=title):
                self.assertIn(
                    "dependabot:title-invalid", validate_live_pull_request(bad)
                )

        human = copy.deepcopy(snapshot)
        human["actor_login"] = "wordingone"
        errors = validate_live_pull_request(human)
        self.assertIn("labels:review-cardinality", errors)
        self.assertIn("body:template-marker-missing", errors)

    def test_valid_human_pr_passes(self) -> None:
        self.assertEqual([], validate_live_pull_request(human_pr()))

    def test_human_pr_requires_live_metadata_and_semantic_sections(self) -> None:
        for field, replacement, expected in (
            ("title", "Fix policy", "title"),
            ("base_sha", "c" * 40, "event-base"),
            ("head_sha", "c" * 40, "event-head"),
            ("milestone", None, "milestone"),
            ("body", human_body().replace("## Claim boundary", "## Missing"), "Claim boundary"),
        ):
            value = human_pr()
            value[field] = replacement
            with self.subTest(field=field):
                self.assertTrue(
                    any(expected in error for error in validate_live_pull_request(value))
                )

    def test_human_pr_enforces_label_cardinality_and_live_milestone(self) -> None:
        value = human_pr()
        value["labels"] = [*value["labels"], "kind:defect"]
        self.assertIn("labels:kind-cardinality", validate_live_pull_request(value))
        value = human_pr()
        value["milestone"] = "EMBER-03"
        self.assertIn("milestone:body-live-mismatch", validate_live_pull_request(value))

    def test_dependabot_has_closed_narrow_schema(self) -> None:
        value = {
            "actor_login": "dependabot[bot]",
            "title": "build(deps): bump actions/checkout from 5 to 6",
            "body": "Bumps actions/checkout from 5 to 6.",
            "base_sha": BASE,
            "head_sha": HEAD,
            "event_base_sha": BASE,
            "event_head_sha": HEAD,
            "draft": False,
            "labels": [
                "kind:maintenance",
                "area:ci",
                "state:ready",
                "priority:p3",
            ],
            "milestone": None,
            "changed_files": [".github/workflows/ci-pr.yml"],
        }
        self.assertEqual([], validate_live_pull_request(value))
        for mutation, expected in (
            ({"title": "feat(runtime): add a feature"}, "dependabot:title"),
            ({"changed_files": ["scripts/github/policy.py"]}, "dependabot:path"),
            ({"labels": ["kind:feature", "area:ci", "state:ready", "priority:p3"]}, "dependabot:labels"),
        ):
            bad = copy.deepcopy(value)
            bad.update(mutation)
            with self.subTest(mutation=mutation):
                self.assertTrue(
                    any(expected in error for error in validate_live_pull_request(bad))
                )

    def test_unknown_fields_and_non_string_file_paths_fail_closed(self) -> None:
        value = human_pr()
        value["unexpected"] = True
        self.assertIn("snapshot:unknown-fields:unexpected", validate_live_pull_request(value))
        value = human_pr()
        value["changed_files"] = [None]
        self.assertIn("snapshot:changed-files-invalid", validate_live_pull_request(value))




class HeadPinBranchUpdateTests(unittest.TestCase):
    """Issue #1350: guard verdicts must be invariant under base branch updates."""

    def _run(self, repo, *args, env=None):
        result = subprocess.run(
            ["git", *args], cwd=repo, capture_output=True, text=True, env=env
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        return result.stdout.strip()

    def setUp(self) -> None:
        self.tmp = tempfile.mkdtemp(prefix="pin-fixture-")
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)
        self.env = dict(
            os.environ,
            GIT_AUTHOR_NAME="fixture",
            GIT_AUTHOR_EMAIL="fixture@example.invalid",
            GIT_COMMITTER_NAME="fixture",
            GIT_COMMITTER_EMAIL="fixture@example.invalid",
        )
        repo = self.tmp
        run = lambda *a: self._run(repo, *a, env=self.env)
        run("init", "-b", "master")
        pathlib.Path(repo, "master_only.txt").write_text("m0\n", encoding="utf-8")
        pathlib.Path(repo, "pr_file.txt").write_text("p0\n", encoding="utf-8")
        run("add", "-A")
        run("commit", "-m", "base")
        self.pinned_base = run("rev-parse", "HEAD")
        run("checkout", "-b", "pr")
        pathlib.Path(repo, "pr_file.txt").write_text("p1\n", encoding="utf-8")
        run("commit", "-am", "pr change")
        self.pinned_head = run("rev-parse", "HEAD")
        run("checkout", "master")
        pathlib.Path(repo, "master_only.txt").write_text("m1\n", encoding="utf-8")
        run("commit", "-am", "unrelated master merge")
        self.master_tip = run("rev-parse", "HEAD")
        run("checkout", "pr")
        run("merge", "--no-edit", "master")
        self.live_head = run("rev-parse", "HEAD")
        run("checkout", "--detach", "master")
        run("merge", "--no-ff", "--no-edit", "pr")
        self.run = run

    def _snapshot(self, *, base: str, head: str, reviewed_head: str) -> dict[str, object]:
        snapshot = human_pr()
        snapshot.update(
            {
                "base_sha": base,
                "head_sha": head,
                "event_base_sha": base,
                "event_head_sha": head,
                "changed_files": ["pr_file.txt"],
                "body": human_body()
                .replace(BASE, self.pinned_base)
                .replace(HEAD, reviewed_head),
            }
        )
        return snapshot

    def test_reviewed_base_survives_unrelated_master_merge_only(self) -> None:
        snapshot = self._snapshot(
            base=self.master_tip,
            head=self.live_head,
            reviewed_head=self.pinned_head,
        )
        self.assertEqual(
            [],
            validate_live_pull_request(
                snapshot,
                base_root=pathlib.Path(self.tmp),
                subject_root=pathlib.Path(self.tmp),
            ),
        )

        self.run("checkout", "master")
        pathlib.Path(self.tmp, "pr_file.txt").write_text(
            "master-overlap\n", encoding="utf-8"
        )
        self.run("commit", "-am", "overlapping master edit")
        overlapping_base = self.run("rev-parse", "HEAD")
        self.run("checkout", "pr")
        merge = subprocess.run(
            ["git", "merge", "--no-edit", "master"],
            cwd=self.tmp,
            capture_output=True,
            text=True,
            env=self.env,
        )
        self.assertNotEqual(merge.returncode, 0)
        pathlib.Path(self.tmp, "pr_file.txt").write_text("p1\n", encoding="utf-8")
        self.run("add", "pr_file.txt")
        self.run("commit", "-m", "resolve overlap with reviewed PR content")
        overlapping_head = self.run("rev-parse", "HEAD")
        self.run("checkout", "--detach", "master")
        self.run("merge", "--no-ff", "--no-edit", "pr")

        tampered = self._snapshot(
            base=overlapping_base,
            head=overlapping_head,
            reviewed_head=overlapping_head,
        )
        self.assertIn(
            "body:base-sha-mismatch",
            validate_live_pull_request(
                tampered,
                base_root=pathlib.Path(self.tmp),
                subject_root=pathlib.Path(self.tmp),
            ),
        )

    def test_pinned_head_survives_unrelated_master_merge(self) -> None:
        self.assertTrue(
            pinned_head_covers_live_head(
                pathlib.Path(self.tmp), self.pinned_head, self.live_head
            )
        )

    def test_post_pin_pr_side_edit_still_fails(self) -> None:
        self.run("checkout", "pr")
        pathlib.Path(self.tmp, "pr_file.txt").write_text("p2\n", encoding="utf-8")
        self.run("commit", "-am", "post-pin edit")
        tampered_head = self.run("rev-parse", "HEAD")
        self.run("checkout", "--detach", "master")
        self.run("merge", "--no-ff", "--no-edit", "pr")
        self.assertFalse(
            pinned_head_covers_live_head(
                pathlib.Path(self.tmp), self.pinned_head, tampered_head
            )
        )

    def test_unrelated_sha_never_accepted(self) -> None:
        self.assertFalse(
            pinned_head_covers_live_head(
                pathlib.Path(self.tmp), self.master_tip, self.live_head
            )
        )

    def test_merge_parent_range_excludes_master_only_files(self) -> None:
        # The workflow's range on the refs/pull/N/merge subject: HEAD^1...HEAD,
        # exercised with the exact diff flags the binding checker runs.
        files = self._run(
            self.tmp,
            "diff", "--find-renames", "--find-copies", "--name-only",
            "--diff-filter=ACMRT", "HEAD^1...HEAD",
            env=self.env,
        ).splitlines()
        self.assertEqual(files, ["pr_file.txt"])

    def test_two_dot_stale_base_range_swept_in_master_files(self) -> None:
        # The pre-fix defect: two-dot from the stale event base sweeps in
        # files the PR never touched.
        stale_base = self._run(
            self.tmp, "rev-list", "--max-parents=0", "HEAD", env=self.env
        )
        files = self._run(
            self.tmp,
            "diff", "--name-only", "--diff-filter=ACMRT",
            f"{stale_base}..HEAD",
            env=self.env,
        ).splitlines()
        self.assertIn("master_only.txt", files)


if __name__ == "__main__":
    unittest.main()
