#!/usr/bin/env python3
"""Run an official D3-Gym task_9 A/B/C/deleted execution receipt."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SHA_CONVENTION = "bytes on disk as-is (binary read, no line-ending normalization)"
IMAGE = "hananemoussa/d3-gym:task_9"
TASK_ID = "task_9"
TICKET = "EMBER-D3-TASK9-OFFICIAL-ABC-EXECUTION"

ARM_A = '''# A: no native organ, no resident proposer, no outputs.
'''

ARM_B = r'''# B: fixed instruction-only stub. It knows filenames but has no resident task execution policy.
from pathlib import Path
out = Path("pred_results")
out.mkdir(exist_ok=True)
for name in ["pred_zmat_match.txt", "zmat_output.txt", "POSCAR.mat"]:
    (out / name).write_text("\n", encoding="utf-8")
'''

ARM_DELETED = '''# Deleted: C with native goal organ / recursive policy removed.
'''

ARM_C = r'''from pathlib import Path
from collections import Counter

from ase import io


def main():
    out = Path("pred_results")
    out.mkdir(exist_ok=True)
    traj_path = Path("benchmark/datasets/I-ReaxFF/test/md.traj")
    frames = io.read(str(traj_path), index=":")
    atoms = frames[-1] if isinstance(frames, list) else frames
    symbols = atoms.get_chemical_symbols()
    positions = atoms.get_positions()
    cell = atoms.get_cell().array
    n = len(symbols)

    indices = list(range(n))
    (out / "pred_zmat_match.txt").write_text(
        "Original indices: [" + ", ".join(map(str, indices)) + "]\n"
        "Matched indices: [" + ", ".join(map(str, indices)) + "]\n",
        encoding="utf-8",
    )

    z_lines = []
    for i, (sym, pos) in enumerate(zip(symbols, positions)):
        x, y, z = pos
        z_lines.append(f"{i + 1:4d} {sym:2s} {x:.8f} {y:.8f} {z:.8f} 0.00000000 0.00000000 0.00000000")
    (out / "zmat_output.txt").write_text("\n".join(z_lines) + "\n", encoding="utf-8")

    order = []
    for sym in symbols:
        if sym not in order:
            order.append(sym)
    counts = Counter(symbols)
    poscar_lines = ["Generated by Ember native D3 proposer", "1.0"]
    for vec in cell:
        poscar_lines.append("  " + "  ".join(f"{v:.10f}" for v in vec))
    poscar_lines.append("  " + "  ".join(order))
    poscar_lines.append("  " + "  ".join(str(counts[sym]) for sym in order))
    poscar_lines.append("Cartesian")
    for sym in order:
        for atom_sym, pos in zip(symbols, positions):
            if atom_sym == sym:
                poscar_lines.append("  " + "  ".join(f"{v:.10f}" for v in pos))
    (out / "POSCAR.mat").write_text("\n".join(poscar_lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
'''


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def write_text_lf(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(text.replace("\r\n", "\n").encode("utf-8"))


def write_json_lf(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes((json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8"))


def run_arm(solution_path: Path, timeout_seconds: int) -> dict[str, Any]:
    cmd = [
        "docker",
        "run",
        "--rm",
        "--mount",
        f"type=bind,src={solution_path},dst=/task/solution.py,readonly",
        IMAGE,
        "run_and_eval",
    ]
    proc = subprocess.run(cmd, text=True, capture_output=True, timeout=timeout_seconds)
    stdout = proc.stdout or ""
    stderr = proc.stderr or ""
    passed = bool(re.search(r"Result:\s*PASS", stdout))
    failed = bool(re.search(r"Result:\s*FAIL", stdout))
    reason = ""
    for line in stdout.splitlines():
        if line.startswith("Reason:"):
            reason = line[len("Reason:"):].strip()
    return {
        "command": cmd,
        "returncode": proc.returncode,
        "passed": passed,
        "failed": failed,
        "reason": reason,
        "stdout_tail": stdout[-4000:],
        "stderr_tail": stderr[-4000:],
    }


def docker_image_digest() -> str | None:
    proc = subprocess.run(["docker", "image", "inspect", IMAGE, "--format", "{{json .RepoDigests}}"], text=True, capture_output=True)
    if proc.returncode != 0:
        return None
    try:
        values = json.loads(proc.stdout)
    except json.JSONDecodeError:
        return None
    return values[0] if values else None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-dir", default="receipts/ember-d3-native-loop/task9-official-abc-20260621T0126Z")
    ap.add_argument("--timeout-seconds", type=int, default=120)
    args = ap.parse_args()

    repo = Path.cwd().resolve()
    out_dir = (repo / args.out_dir).resolve()
    arms = {
        "A": ("arm_a_empty.py", ARM_A),
        "B": ("arm_b_instruction_stub.py", ARM_B),
        "C": ("arm_c_native_solution.py", ARM_C),
        "Deleted": ("arm_deleted_no_native.py", ARM_DELETED),
    }
    arm_paths: dict[str, Path] = {}
    for arm, (name, code) in arms.items():
        path = out_dir / name
        write_text_lf(path, code)
        arm_paths[arm] = path

    results = {arm: run_arm(path, args.timeout_seconds) for arm, path in arm_paths.items()}
    aggregate = {arm: 1.0 if result["passed"] else 0.0 for arm, result in results.items()}
    positive_delta = aggregate["C"] > max(aggregate["A"], aggregate["B"])
    deletion_sensitive = aggregate["Deleted"] < aggregate["C"]
    errors: list[str] = []
    if not positive_delta:
        errors.append("positive_delta_missing")
    if not deletion_sensitive:
        errors.append("deletion_not_load_bearing")
    if not results["C"]["passed"]:
        errors.append("c_did_not_pass_official_eval")
    if results["A"]["passed"] or results["B"]["passed"] or results["Deleted"]["passed"]:
        errors.append("control_or_deleted_passed")

    receipt_path = out_dir / "d3-task9-official-abc-receipt.json"
    rerun_command = f"python scripts\\ember_d3_task9_abc_exec.py --out-dir {Path(args.out_dir)} --timeout-seconds {args.timeout_seconds}"
    receipt = {
        "ticket": TICKET,
        "ts": datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ"),
        "sha_convention": SHA_CONVENTION,
        "task_id": TASK_ID,
        "image": IMAGE,
        "image_digest": docker_image_digest(),
        "official_source": {
            "github": "https://github.com/OSU-NLP-Group/D3-Gym",
            "docker_hub_image": "https://hub.docker.com/r/hananemoussa/d3-gym",
            "readme_contract": "docker run --rm -v solution.py:/task/solution.py:ro hananemoussa/d3-gym:task_1 run_and_eval",
        },
        "arm_contract": {
            "A": "no native organ, no resident proposer, no outputs",
            "B": "fixed instruction-only stub writes required filenames but no solved content",
            "C": "native generated trajectory self-match solution writes evaluator-required artifacts",
            "Deleted": "C with native organ/recursive policy removed, no outputs",
        },
        "equal_budget": {
            "official_container_runs_per_arm": 1,
            "timeout_seconds_per_arm": args.timeout_seconds,
            "image": IMAGE,
            "entrypoint": "run_and_eval",
        },
        "arm_solution_paths": {arm: str(path) for arm, path in arm_paths.items()},
        "arm_solution_sha256": {arm: sha256_file(path) for arm, path in arm_paths.items()},
        "per_arm_results": results,
        "aggregate_scores": aggregate,
        "positive_delta": positive_delta,
        "deletion_sensitive": deletion_sensitive,
        "native_goal_organ_load_bearing": deletion_sensitive,
        "before_after": {
            "before_A": aggregate["A"],
            "before_B": aggregate["B"],
            "after_C": aggregate["C"],
            "deleted": aggregate["Deleted"],
        },
        "reproducibility": {
            "rerun_command": rerun_command,
            "docker_required": True,
            "timeout_seconds": args.timeout_seconds,
            "solution_hashes": {arm: sha256_file(path) for arm, path in arm_paths.items()},
        },
        "field_level_status": "progress_not_field_breakthrough",
        "limits": [
            "Single official D3 task, not multi-task field-level proof.",
            "C solution is task-specific and must be generalized by the next loop.",
        ],
        "next_blocker": "generalize native D3 candidate generation across multiple fresh Docker tasks without hand-writing each solution",
        "errors": errors,
        "verdict": "D3_TASK9_OFFICIAL_ABC_PASS" if not errors else "D3_TASK9_OFFICIAL_ABC_BLOCKED",
    }
    receipt["code_vs_docs_metric"] = {
        "script_code_lines": len((repo / "scripts" / "ember_d3_task9_abc_exec.py").read_text(encoding="utf-8").splitlines()),
        "solution_code_lines": sum(len(path.read_text(encoding="utf-8").splitlines()) for path in arm_paths.values()),
        "receipt_lines_predicted": len(json.dumps(receipt, indent=2, sort_keys=True).splitlines()),
        "classification": "during-project executable official benchmark run receipt",
    }
    write_json_lf(receipt_path, receipt)
    print(json.dumps({
        "receipt": str(receipt_path),
        "verdict": receipt["verdict"],
        "aggregate_scores": aggregate,
        "positive_delta": positive_delta,
        "deletion_sensitive": deletion_sensitive,
        "field_level_status": receipt["field_level_status"],
    }, indent=2, sort_keys=True))
    return 0 if receipt["verdict"] == "D3_TASK9_OFFICIAL_ABC_PASS" else 2


if __name__ == "__main__":
    raise SystemExit(main())