#!/usr/bin/env python3
"""gen_readme_status.py — regenerate README.md's board-status block from the newest totality receipt.

Reads the newest scripts/ember_totality/receipts-totality/ember-totality-*.json (lexicographic
sort of the ts-stamped filename == chronological order) and rewrites everything between the
<!-- BOARD-STATUS-BEGIN --> / <!-- BOARD-STATUS-END --> markers in README.md with: the receipt
id, its ts, counts by status, and a one-line legend. This makes a stale README count structurally
impossible -- the block can only ever say what the newest receipt on disk says.

Board-run playbook: run this script (python scripts/gen_readme_status.py) as the last step of
every totality board run, so README never drifts from the board.

CLI:
  python scripts/gen_readme_status.py            # regenerate README.md in place
  python scripts/gen_readme_status.py --check     # exit 1 if README.md would change (CI use)

Stdlib only. No network.
"""
import argparse
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RECEIPTS_GLOB = os.path.join(ROOT, "scripts", "ember_totality", "receipts-totality", "ember-totality-*.json")
README_PATH = os.path.join(ROOT, "README.md")
BEGIN_MARKER = "<!-- BOARD-STATUS-BEGIN -->"
END_MARKER = "<!-- BOARD-STATUS-END -->"


def newest_receipt_path():
    paths = sorted(glob.glob(RECEIPTS_GLOB))
    if not paths:
        raise SystemExit(
            "gen_readme_status: no ember-totality-*.json receipts found under "
            "scripts/ember_totality/receipts-totality/"
        )
    return paths[-1]


def render_block(receipt_path):
    with open(receipt_path, "r", encoding="utf-8") as f:
        receipt = json.load(f)
    receipt_id = os.path.splitext(os.path.basename(receipt_path))[0]
    ts = receipt.get("ts", "unknown")
    summary = receipt.get("summary", {})
    green = summary.get("green", 0)
    red = summary.get("red", 0)
    unevaluable = summary.get("unevaluable", 0)
    audit_ok = summary.get("audit_ok", 0)
    audit_incident = summary.get("audit_incident", 0)
    audit_pending_epoch = summary.get("audit_pending_epoch", 0)
    total = summary.get(
        "total",
        green + red + unevaluable + audit_ok + audit_incident + audit_pending_epoch,
    )
    pct_green = summary.get("pct_green", 0.0)
    lines = [
        BEGIN_MARKER,
        "<!-- GENERATED by scripts/gen_readme_status.py -- do not hand-edit between the markers -->",
        f"**Board receipt:** `{receipt_id}` (ts `{ts}`).",
        "",
        f"**Counts:** {green}-GREEN / {red}-RED / {unevaluable}-UNEVALUABLE / "
        f"{audit_ok}-AUDIT-OK / {audit_incident}-AUDIT-INCIDENT / "
        f"{audit_pending_epoch}-AUDIT-PENDING-EPOCH (total {total} rows, "
        f"{pct_green}% of state-conditions GREEN).",
        "",
        "**Legend:** GREEN = a fresh receipt satisfies the condition's CHK; RED = CHK unmet or a "
        "satisfying artifact is absent; UNEVALUABLE = the probe genuinely cannot look (counts as "
        "RED for completion math); AUDIT-OK/AUDIT-INCIDENT/AUDIT-PENDING-EPOCH = the three "
        "standing process-invariant rows (cadence-audit results, never a completion conjunct).",
        END_MARKER,
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if README.md's board-status block is not already current (no write)",
    )
    args = parser.parse_args()

    receipt_path = newest_receipt_path()
    block = render_block(receipt_path)

    with open(README_PATH, "r", encoding="utf-8") as f:
        readme = f.read()

    pattern = re.compile(re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
    if not pattern.search(readme):
        raise SystemExit(
            f"gen_readme_status: README.md is missing the {BEGIN_MARKER} ... {END_MARKER} markers"
        )
    new_readme = pattern.sub(lambda _: block, readme, count=1)

    if new_readme == readme:
        print(f"README.md board-status block already current ({os.path.basename(receipt_path)}).")
        return 0

    if args.check:
        print(f"README.md board-status block is STALE vs {os.path.basename(receipt_path)}.")
        return 1

    with open(README_PATH, "w", encoding="utf-8") as f:
        f.write(new_readme)
    print(f"README.md board-status block regenerated from {os.path.basename(receipt_path)}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
