#!/usr/bin/env python3
# goal_id: EMBER-02
# workstream_id: EMBER-02A
# next_executed_outcome: EMBER-02 first sufficiently pretrained clean-genesis 3B Ember
"""gen_readme_status.py — regenerate README.md's board-status block from the newest totality receipt.

Reads the newest ember-totality-*.json under a receipts-totality directory (lexicographic sort of
the ts-stamped filename == chronological order) and rewrites everything between the
<!-- BOARD-STATUS-BEGIN --> / <!-- BOARD-STATUS-END --> markers in README.md with: the receipt
id, its ts, counts by status, and a one-line legend. This makes a stale README count structurally
impossible for whatever receipt tree the script was pointed at -- the block can only ever say
what the newest receipt in THAT tree says.

**"Newest" is scoped to --data-root, not to the world.** By default this reads
scripts/ember_totality/receipts-totality/ under this repo -- the newest receipt COMMITTED to this
checkout. A board-run lane's live data tree (uncommitted local receipts, or a different working
copy) can genuinely hold a newer receipt than what's tracked here; that receipt is invisible to
this script until it (or a copy of it) lands under --data-root. The generated block's stamped
receipt id is the honest disclosure either way -- it never claims to be "current," only to match
the newest receipt the script could see.

Board-run playbook:
  - A board-run lane with a live data tree runs this against that tree BEFORE committing anything:
    `python scripts/gen_readme_status.py --data-root /path/to/live/receipts-totality --check`
    to see whether README would change, then without --check to render it, then reviews the diff.
  - Run this script as the last step of every totality board run against the tree that will
    actually be committed, so README never drifts from what ships in the same commit.
  - If README changes as a result, land it as its own docs PR through the normal stop-at-open
    review flow -- this script never commits or pushes on its own.

CLI:
  python scripts/gen_readme_status.py            # regenerate README.md from the in-repo tree
  python scripts/gen_readme_status.py --check     # exit 1 if README.md would change (CI use)
  python scripts/gen_readme_status.py --data-root /path/to/receipts-totality
                                                  # point at a different (e.g. live/uncommitted)
                                                  # receipts-totality directory instead

Stdlib only. No network.
"""
import argparse
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_DATA_ROOT = os.path.join(ROOT, "scripts", "ember_totality", "receipts-totality")
README_PATH = os.path.join(ROOT, "README.md")
CONTINUITY_PATH = os.path.join(ROOT, "CONTINUITY.md")
CURRENT_SUBJECT_PATH = os.path.join(ROOT, "manifests", "ember-current-subject-v1.json")
BEGIN_MARKER = "<!-- BOARD-STATUS-BEGIN -->"
END_MARKER = "<!-- BOARD-STATUS-END -->"
SUBJECT_BEGIN_MARKER = "<!-- CURRENT-SUBJECT-BEGIN -->"
SUBJECT_END_MARKER = "<!-- CURRENT-SUBJECT-END -->"


def newest_receipt_path(data_root):
    receipts_glob = os.path.join(data_root, "ember-totality-*.json")
    paths = sorted(glob.glob(receipts_glob))
    if not paths:
        raise SystemExit(
            f"gen_readme_status: no ember-totality-*.json receipts found under {data_root}"
        )
    return paths[-1]


def render_block(receipt_path):
    with open(receipt_path, "r", encoding="utf-8") as f:
        receipt = json.load(f)
    receipt_id = os.path.splitext(os.path.basename(receipt_path))[0]
    ts = receipt.get("ts", "unknown")
    summary = receipt.get("summary", {})
    green = summary.get("green", 0)
    red = summary.get("red", 0)
    unevaluable = summary.get("unevaluable", 0)
    audit_ok = summary.get("audit_ok", 0)
    audit_incident = summary.get("audit_incident", 0)
    audit_pending_epoch = summary.get("audit_pending_epoch", 0)
    total = summary.get(
        "total",
        green + red + unevaluable + audit_ok + audit_incident + audit_pending_epoch,
    )
    pct_green = summary.get("pct_green", 0.0)
    lines = [
        BEGIN_MARKER,
        "<!-- GENERATED by scripts/gen_readme_status.py -- do not hand-edit between the markers -->",
        f"**Board receipt:** `{receipt_id}` (ts `{ts}`).",
        "",
        f"**Counts:** {green}-GREEN / {red}-RED / {unevaluable}-UNEVALUABLE / "
        f"{audit_ok}-AUDIT-OK / {audit_incident}-AUDIT-INCIDENT / "
        f"{audit_pending_epoch}-AUDIT-PENDING-EPOCH (total {total} rows, "
        f"{pct_green}% of state-conditions GREEN).",
        "",
        "**Legend:** GREEN = a fresh receipt satisfies the condition's CHK; RED = CHK unmet or a "
        "satisfying artifact is absent; UNEVALUABLE = the probe genuinely cannot look (counts as "
        "RED for completion math); AUDIT-OK/AUDIT-INCIDENT/AUDIT-PENDING-EPOCH = the three "
        "standing process-invariant rows (cadence-audit results, never a completion conjunct).",
        END_MARKER,
    ]
    return "\n".join(lines)


def _closed_hash(value, field):
    if not isinstance(value, str) or not re.fullmatch(r"[0-9a-f]{64}", value):
        raise ValueError(f"current subject {field} must be lowercase SHA-256")
    return value


def load_current_subject(path):
    with open(path, "r", encoding="utf-8") as stream:
        payload = json.load(stream)
    if (
        not isinstance(payload, dict)
        or payload.get("schema_version") != "ember-current-subject-v1"
    ):
        raise ValueError("current subject schema_version must be ember-current-subject-v1")
    authority = payload.get("authority")
    if not isinstance(authority, dict) or set(authority) != {
        "goal_id",
        "workstream_id",
        "next_executed_outcome",
    }:
        raise ValueError("current subject authority binding is not closed")
    subject = payload.get("subject")
    if not isinstance(subject, dict):
        raise ValueError("current subject payload is missing")
    for field in (
        "checkpoint_manifest_sha256",
        "model_config_sha256",
        "tokenizer_sha256",
        "optimizer_state_sha256",
    ):
        _closed_hash(subject.get(field), field)
    cursor = subject.get("token_cursor")
    if not isinstance(cursor, dict) or set(cursor) != {
        "global_step",
        "record_index",
        "token_offset",
        "tokens_seen",
    }:
        raise ValueError("current subject token_cursor is not closed")
    if not all(isinstance(value, int) and value >= 0 for value in cursor.values()):
        raise ValueError("current subject token_cursor values must be nonnegative integers")
    parameters = subject.get("parameters")
    if not isinstance(parameters, dict) or set(parameters) != {
        "active",
        "allocated",
        "episode_trainable",
        "served",
        "trainable",
        "unique",
    }:
        raise ValueError("current subject parameter counts are not closed")
    if not all(isinstance(value, int) and value > 0 for value in parameters.values()):
        raise ValueError("current subject parameter counts must be positive integers")
    evidence = subject.get("evidence_paths")
    if (
        not isinstance(evidence, list)
        or not evidence
        or evidence != sorted(evidence)
        or not all(
            isinstance(item, str)
            and item
            and not os.path.isabs(item)
            and not re.match(r"^[A-Za-z]:", item)
            for item in evidence
        )
    ):
        raise ValueError("current subject evidence_paths must be sorted repo-relative paths")
    return payload


def render_current_subject_block(payload):
    subject = payload["subject"]
    cursor = subject["token_cursor"]
    parameters = subject["parameters"]
    predecessor = subject["predecessor"]
    return "\n".join(
        [
            SUBJECT_BEGIN_MARKER,
            "<!-- GENERATED by scripts/gen_readme_status.py from manifests/ember-current-subject-v1.json -->",
            f"**Current checkpoint subject:** `{subject['checkpoint_manifest_sha256']}`.",
            "",
            f"- Disposition: `{subject['disposition']}`; capability credit: `{subject['capability_credit']}`; sufficient pretraining proven: `{str(subject['sufficient_pretraining_proven']).lower()}`.",
            f"- Config: `{subject['model_config_sha256']}`; tokenizer: `{subject['tokenizer_sha256']}`; optimizer state: `{subject['optimizer_state_sha256']}`.",
            f"- Cursor: step `{cursor['global_step']}`, record `{cursor['record_index']}`, token offset `{cursor['token_offset']}`, tokens seen `{cursor['tokens_seen']}`; active route: `{subject['active_route']}`.",
            f"- Parameters: `{parameters['unique']}` unique, `{parameters['trainable']}` trainable, `{parameters['served']}` served, `{parameters['active']}` active, `{parameters['episode_trainable']}` episode-trainable.",
            f"- Historical predecessor: `{predecessor['checkpoint_manifest_sha256']}` at `{predecessor['tokens_seen']}` tokens (`{predecessor['relationship']}`).",
            SUBJECT_END_MARKER,
        ]
    )


def _replace_marked(text, begin, end, block, surface):
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    matches = pattern.findall(text)
    if len(matches) != 1:
        raise ValueError(f"{surface} must contain exactly one {begin} ... {end} block")
    return pattern.sub(lambda _: block, text, count=1)


def subject_surfaces_current(payload, readme_path, continuity_path):
    block = render_current_subject_block(payload)
    try:
        with open(readme_path, "r", encoding="utf-8") as stream:
            readme = stream.read()
        with open(continuity_path, "r", encoding="utf-8") as stream:
            continuity = stream.read()
        return (
            _replace_marked(
                readme,
                SUBJECT_BEGIN_MARKER,
                SUBJECT_END_MARKER,
                block,
                "README.md",
            )
            == readme
            and _replace_marked(
                continuity,
                SUBJECT_BEGIN_MARKER,
                SUBJECT_END_MARKER,
                block,
                "CONTINUITY.md",
            )
            == continuity
        )
    except (OSError, ValueError):
        return False


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if README.md's board-status block is not already current (no write)",
    )
    parser.add_argument(
        "--data-root",
        default=DEFAULT_DATA_ROOT,
        help=(
            "directory to scan for ember-totality-*.json (default: this repo's "
            "scripts/ember_totality/receipts-totality/). Point this at a board-run lane's live "
            "data tree to render against a receipt not yet committed here."
        ),
    )
    parser.add_argument("--readme", default=README_PATH)
    parser.add_argument("--continuity", default=CONTINUITY_PATH)
    parser.add_argument("--subject-manifest", default=CURRENT_SUBJECT_PATH)
    args = parser.parse_args()

    receipt_path = newest_receipt_path(args.data_root)
    block = render_block(receipt_path)

    with open(args.readme, "r", encoding="utf-8") as f:
        readme = f.read()

    pattern = re.compile(re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
    if not pattern.search(readme):
        raise SystemExit(
            f"gen_readme_status: README.md is missing the {BEGIN_MARKER} ... {END_MARKER} markers"
        )
    new_readme = pattern.sub(lambda _: block, readme, count=1)

    subject = load_current_subject(args.subject_manifest)
    subject_block = render_current_subject_block(subject)
    new_readme = _replace_marked(
        new_readme,
        SUBJECT_BEGIN_MARKER,
        SUBJECT_END_MARKER,
        subject_block,
        "README.md",
    )
    with open(args.continuity, "r", encoding="utf-8") as stream:
        continuity = stream.read()
    new_continuity = _replace_marked(
        continuity,
        SUBJECT_BEGIN_MARKER,
        SUBJECT_END_MARKER,
        subject_block,
        "CONTINUITY.md",
    )

    if new_readme == readme and new_continuity == continuity:
        print(
            "README.md board-status and current-subject surfaces already current "
            f"({os.path.basename(receipt_path)})."
        )
        return 0

    if args.check:
        print("README.md or CONTINUITY.md generated status is STALE.")
        return 1

    with open(args.readme, "w", encoding="utf-8") as f:
        f.write(new_readme)
    with open(args.continuity, "w", encoding="utf-8") as stream:
        stream.write(new_continuity)
    print(
        "README.md and CONTINUITY.md status surfaces regenerated from "
        f"{os.path.basename(receipt_path)} and {os.path.basename(args.subject_manifest)}."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
