#!/usr/bin/env python3
"""gen_readme_status.py — regenerate README.md's board-status block from the newest totality receipt.

Reads the newest ember-totality-*.json under a receipts-totality directory (lexicographic sort of
the ts-stamped filename == chronological order) and rewrites everything between the
<!-- BOARD-STATUS-BEGIN --> / <!-- BOARD-STATUS-END --> markers in README.md with: the receipt
id, its ts, counts by status, and a one-line legend. This makes a stale README count structurally
impossible for whatever receipt tree the script was pointed at -- the block can only ever say
what the newest receipt in THAT tree says.

**"Newest" is scoped to --data-root, not to the world.** By default this reads
scripts/ember_totality/receipts-totality/ under this repo -- the newest receipt COMMITTED to this
checkout. A board-run lane's live data tree (uncommitted local receipts, or a different working
copy) can genuinely hold a newer receipt than what's tracked here; that receipt is invisible to
this script until it (or a copy of it) lands under --data-root. The generated block's stamped
receipt id is the honest disclosure either way -- it never claims to be "current," only to match
the newest receipt the script could see.

Board-run playbook:
  - A board-run lane with a live data tree runs this against that tree BEFORE committing anything:
    `python scripts/gen_readme_status.py --data-root /path/to/live/receipts-totality --check`
    to see whether README would change, then without --check to render it, then reviews the diff.
  - Run this script as the last step of every totality board run against the tree that will
    actually be committed, so README never drifts from what ships in the same commit.
  - If README changes as a result, land it as its own docs PR through the normal stop-at-open
    review flow -- this script never commits or pushes on its own.

CLI:
  python scripts/gen_readme_status.py            # regenerate README.md from the in-repo tree
  python scripts/gen_readme_status.py --check     # exit 1 if README.md would change (CI use)
  python scripts/gen_readme_status.py --data-root /path/to/receipts-totality
                                                  # point at a different (e.g. live/uncommitted)
                                                  # receipts-totality directory instead

Stdlib only. No network.
"""
import argparse
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_DATA_ROOT = os.path.join(ROOT, "scripts", "ember_totality", "receipts-totality")
README_PATH = os.path.join(ROOT, "README.md")
BEGIN_MARKER = "<!-- BOARD-STATUS-BEGIN -->"
END_MARKER = "<!-- BOARD-STATUS-END -->"


def newest_receipt_path(data_root):
    receipts_glob = os.path.join(data_root, "ember-totality-*.json")
    paths = sorted(glob.glob(receipts_glob))
    if not paths:
        raise SystemExit(
            f"gen_readme_status: no ember-totality-*.json receipts found under {data_root}"
        )
    return paths[-1]


def render_block(receipt_path):
    with open(receipt_path, "r", encoding="utf-8") as f:
        receipt = json.load(f)
    receipt_id = os.path.splitext(os.path.basename(receipt_path))[0]
    ts = receipt.get("ts", "unknown")
    summary = receipt.get("summary", {})
    green = summary.get("green", 0)
    red = summary.get("red", 0)
    unevaluable = summary.get("unevaluable", 0)
    audit_ok = summary.get("audit_ok", 0)
    audit_incident = summary.get("audit_incident", 0)
    audit_pending_epoch = summary.get("audit_pending_epoch", 0)
    total = summary.get(
        "total",
        green + red + unevaluable + audit_ok + audit_incident + audit_pending_epoch,
    )
    pct_green = summary.get("pct_green", 0.0)
    lines = [
        BEGIN_MARKER,
        "<!-- GENERATED by scripts/gen_readme_status.py -- do not hand-edit between the markers -->",
        f"**Board receipt:** `{receipt_id}` (ts `{ts}`).",
        "",
        f"**Counts:** {green}-GREEN / {red}-RED / {unevaluable}-UNEVALUABLE / "
        f"{audit_ok}-AUDIT-OK / {audit_incident}-AUDIT-INCIDENT / "
        f"{audit_pending_epoch}-AUDIT-PENDING-EPOCH (total {total} rows, "
        f"{pct_green}% of state-conditions GREEN).",
        "",
        "**Legend:** GREEN = a fresh receipt satisfies the condition's CHK; RED = CHK unmet or a "
        "satisfying artifact is absent; UNEVALUABLE = the probe genuinely cannot look (counts as "
        "RED for completion math); AUDIT-OK/AUDIT-INCIDENT/AUDIT-PENDING-EPOCH = the three "
        "standing process-invariant rows (cadence-audit results, never a completion conjunct).",
        END_MARKER,
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if README.md's board-status block is not already current (no write)",
    )
    parser.add_argument(
        "--data-root",
        default=DEFAULT_DATA_ROOT,
        help=(
            "directory to scan for ember-totality-*.json (default: this repo's "
            "scripts/ember_totality/receipts-totality/). Point this at a board-run lane's live "
            "data tree to render against a receipt not yet committed here."
        ),
    )
    args = parser.parse_args()

    receipt_path = newest_receipt_path(args.data_root)
    block = render_block(receipt_path)

    with open(README_PATH, "r", encoding="utf-8") as f:
        readme = f.read()

    pattern = re.compile(re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
    if not pattern.search(readme):
        raise SystemExit(
            f"gen_readme_status: README.md is missing the {BEGIN_MARKER} ... {END_MARKER} markers"
        )
    new_readme = pattern.sub(lambda _: block, readme, count=1)

    if new_readme == readme:
        print(f"README.md board-status block already current ({os.path.basename(receipt_path)}).")
        return 0

    if args.check:
        print(f"README.md board-status block is STALE vs {os.path.basename(receipt_path)}.")
        return 1

    with open(README_PATH, "w", encoding="utf-8") as f:
        f.write(new_readme)
    print(f"README.md board-status block regenerated from {os.path.basename(receipt_path)}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
